apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-server
  namespace: filterfacts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-server
  template:
    metadata:
      labels:
        app: ai-server
    spec:
      nodeSelector:
        nks.naver.com/nodepool: ai-pool
      imagePullSecrets:
        - name: ncr-secret
      containers:
        - name: ai-server
          image: refactoring-registry.kr.ncr.ntruss.com/ai-server:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: f-f-secret
---
apiVersion: v1
kind: Service
metadata:
  name: ai-server-service
  namespace: filterfacts
spec:
  selector:
    app: ai-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
