apiVersion: v1
kind: Namespace
metadata:
  name: filterfacts

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
  namespace: filterfacts
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nks-block-storage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: filterfacts
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      imagePullSecrets:
        - name: ncr-secret
      containers:
        - name: ollama
          image: refactoring-registry.kr.ncr.ntruss.com/ollama:latest
          ports:
            - containerPort: 11434

          resources:
            requests:
              cpu: "1000m"
              memory: "1.5Gi"
            limits:
              cpu: "2"
              memory: "4Gi"

          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama

      volumes:
        - name: ollama-data
          persistentVolumeClaim:
            claimName: ollama-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: filterfacts
spec:
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
  type: ClusterIP
