apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: filterfacts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - ai-pool-w-f6ec

      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: f-f-postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: f-f-postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: f-f-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATA                 # 🔥 반드시 여기에 있어야 함
              value: /var/lib/postgresql/data/pgdata

          volumeMounts:
            - name: postgres-volume
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: postgres-pvc
