apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379

          # 🔥 redis.conf를 사용해서 Redis 보안(비밀번호) 활성화
          command: ["redis-server", "--requirepass", "$(REDIS_PASSWORD)"]

          envFrom:
            - secretRef:
                name: f-f-redis-secret

          volumeMounts:
            - name: redis-conf
              mountPath: /usr/local/etc/redis/
            - name: redis-data
              mountPath: /data

      volumes:
        - name: redis-conf
          configMap:
            name: redis-config
            items:
              - key: redis.conf
                path: redis.conf

        - name: redis-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379

